config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  devise_for :users
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
  end
  get 'likes/create'
  get 'comment/new'
  get 'comment/create'
  post '/create/:id', to: "comments#create"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can :manage, Comment, author: user
    can :manage, Post, author: user
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :count_comments

  private

  def count_comments
    post.increment(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :count_likes

  private

  def count_likes
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :count_post

  def recent_comments
    comments.order('created_at Desc').limit(5)
  end

  private

  def count_post
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  after_initialize :default_values

  def recent_posts
    posts.order(created_at: :DESC).limit(3)
  end

  def admin?
    role == 'admin'
  end

  private

  def default_values
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:id])
    @comment = current_user.comments.new(text: params[:comment])
    @comment.post_id = @post.id
    if @comment.save
      redirect_to user_post_path(current_user.id, @post.id)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(@comment.post_id)
    redirect_to user_path(current_user.id), notice: 'Comment deleted.'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new
    @like.post_id = @post.id
    @like.author_id = current_user.id
    @like.save
    redirect_to "/user/#{current_user.id}/post/#{@post.id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes([:comments])
  end

  def show
    @post = Post.includes(:author).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    @post.likes_counter = 0
    @post.comments_counter = 0
    if @post.save
      redirect_to user_posts_path(@user.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.author), notice: 'Post Deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="user_post">
  <%= link_to "#{post.title}", user_post_path(@user.id, post.id), class:"post_title" %>
  <p> <%= post.text %> </p>
  <div class="post_info">
    <span>Comments: <%= post.comments_counter %></span>
    <span>Likes: <%= post.likes_counter %></span>
  </div>
  <div class="post_comments">
    <% post.recent_comments.each do |comment| %>
      <span><%= comment.author.name %>: <%= comment.text %></span>
    <%end%>
  </div>
</div>

app/views/posts/index.html.erb
<section class="user_posts">
  <div class="user_wrapper">
  <span class="post_number">
  <a href="<%= @user.photo %>">Photo</a>
  </span>
  <div class="user_info">
    <h2><%= @user.name %></h2>
    <span>
    Number of posts:
    <%= @user.posts_counter%>
    <% if @user.posts_counter.nil?%>
    <%= "0" %>
    <%end%>
    </span>
  </div>
  </div>

  <% @posts.each do |post| %>
    <%= render post %>
  <%end%>
  <%= link_to "New Post", new_user_post_path %>
  <button type="button">Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= form_with url: user_posts_path, scope: :post do |f| %>
  <div>
    <%= f.text_field :title, placeholder:"Title" %>
  </div>
  <div>
    <%= f.text_area :text, placeholder:"Write something here" %>
  </div>
  <%= f.submit "Post" %>
<%end%>

app/views/posts/show.html.erb
<section class="post_details">
  <div class="post">
    <div class="post_heading">
      <span><%= @post.title %> by <%= @post.author.name %></span>
      <%= button_to 'Like', user_post_likes_path(@post.author, @post), method: :post %>
       <div class="post_info">
        <span>Comments: <%= @post.comments_counter %></span>
        <span>Likes: <%= @post.likes_counter %></span>
      </div>
    </div>
    <div class="post_content">
      <p> <%= @post.text %> </p>
    </div>
  </div>
  <div class="post_comments">
    <% @post.comments.each do |comment| %>
      <span><%= comment.author.name %>: <%= comment.text %></span>
      <% if can? :delete, comment %>
      <%= button_to "Delete this comment", user_post_comment_path(comment.author, comment.post, comment), method: :delete %>
      <%end%>
    <%end%>
  </div>
  <div class="add_comment">
    <%= form_with model: @comment, url: "/create/#{@post.id}", method: :post, local: true, data: {turbo: false} do |f| %>
      <div class="comment_field">
        <%= f.text_area :comment, placeholder: "Type your comment", required: true %>
      </div>
      <%= f.submit "Post" %>
    <%end%>
  </div>
  <% if can? :destroy, @post %>
    <%= button_to "Delete this post", user_post_path(@post.author, @post), method: :delete %>
  <%end%>
</section>

app/views/users/_user.html.erb
<div class="user_wrapper">
  <span class="post_number"><%= link_to "Picture", user %></span>
  <div class="user_info">
    <h2><%= user.name %></h2>
    <span>
    Number of posts:
    <%= user.posts_counter%>
    <% if user.posts_counter.nil?%>
    <%= "0" %>
    <%end%>
    </span>
  </div>
</div>

app/views/users/index.html.erb
<section class="users">
  <% @users.each do |user| %>
  <%= render user%>
  <%end%>
</section>

app/views/users/show.html.erb
<section class="user_details">
  <div class="user_wrapper">
  <span class="post_number">
  <a href="<%= @user.photo %>">Photo</a>
  </span>
  <div class="user_info">
    <h2><%= @user.name %></h2>
    <span>
    Number of posts:
    <%= @user.posts_counter%>
    <% if @user.posts_counter.nil?%>
    <%= "0" %>
    <%end%>
    </span>
  </div>
</div>
  <div class="user_bio">
    <span>Bio:</span>
    <p><%= @user.bio %></p>
  </div>
  <% @user.recent_posts.each do |post| %>
    <div class="post_wrapper">
      <h2><%= post.title %></h2>
      <p><%= post.text %></p>
      <div class="post_info">
        <span>Comments: <%= post.comments_counter %></span>
        <span>Likes: <%= post.likes_counter %></span>
      </div>
    </div>
  <%end%>
  <%= link_to "See all posts", user_posts_path(@user), class:"see_all" %>
</section>